[package]
name = "suwen_api"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }


[dependencies]
axum = { workspace = true }
axum-reverse-proxy = { workspace = true }
tower-http = { workspace = true }
