[package]
name = "suwen_entity"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[lib]
name = "suwen_entity"
path = "src/lib.rs"

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
