//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "content"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub content_metadata_id: i32,
    pub lang_code: String,
    pub summary: Option<String>,
    pub intro: Option<String>,
    pub title: String,
    pub original_text: String,
    pub rendered_html: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ContentMetadataId,
    LangCode,
    Summary,
    Intro,
    Title,
    OriginalText,
    RenderedHtml,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ContentMetadata,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::ContentMetadataId => ColumnType::Integer.def(),
            Self::LangCode => ColumnType::Text.def(),
            Self::Summary => ColumnType::Text.def(),
            Self::Intro => ColumnType::Text.def(),
            Self::Title => ColumnType::Text.def(),
            Self::OriginalText => ColumnType::Text.def(),
            Self::RenderedHtml => ColumnType::Text.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ContentMetadata => Entity::belongs_to(super::content_metadata::Entity)
                .from(Column::ContentMetadataId)
                .to(super::content_metadata::Column::Id)
                .into(),
        }
    }
}

impl Related<super::content_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
