//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::FromJsonQueryResult;
use serde::{Deserialize, Serialize};

pub mod prelude;

pub mod comment;
pub mod content;
pub mod content_metadata;
pub mod content_metadata_tag;
pub mod identity;
pub mod like;
pub mod site;
pub mod tag;
pub mod user;

pub use site::{RelatedLink, RelatedLinks, Tab, Tabs};

pub use content::{Toc, TocItem};

// Reference: https://www.sea-ql.org/SeaORM/docs/generate-entity/column-types/#json-column
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct VecString(pub Vec<String>);

impl From<Vec<String>> for VecString {
    fn from(v: Vec<String>) -> Self {
        VecString(v)
    }
}

impl From<Vec<RelatedLink>> for RelatedLinks {
    fn from(v: Vec<RelatedLink>) -> Self {
        RelatedLinks(v)
    }
}

impl From<Vec<Tab>> for Tabs {
    fn from(v: Vec<Tab>) -> Self {
        Tabs(v)
    }
}

impl From<Vec<TocItem>> for Toc {
    fn from(v: Vec<TocItem>) -> Self {
        Toc(v)
    }
}
