//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::FromJsonQueryResult;
use serde::{Deserialize, Serialize};

pub mod prelude;

pub mod content;
pub mod content_metadata;
pub mod content_metadata_tag;
pub mod site;
pub mod tag;
pub mod user;

pub use site::{RelatedLink, Tab, VecRelatedLink, VecTab};

// Reference: https://www.sea-ql.org/SeaORM/docs/generate-entity/column-types/#json-column
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct VecString(pub Vec<String>);

impl Into<VecString> for Vec<String> {
    fn into(self) -> VecString {
        VecString(self)
    }
}

impl Into<VecRelatedLink> for Vec<RelatedLink> {
    fn into(self) -> VecRelatedLink {
        VecRelatedLink(self)
    }
}

impl Into<VecTab> for Vec<Tab> {
    fn into(self) -> VecTab {
        VecTab(self)
    }
}
